import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const { resolvedTheme, systemTheme, theme, setTheme } = useTheme();
  const currentTheme = theme === "system" ? systemTheme : theme;
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  let src;

  switch (resolvedTheme) {
    case "light":
      src = "/moon.svg";
      break;
    case "dark":
      src = "/sun.svg";
      break;
    default:
      src = "/thirteen.svg";
      break;
  }
  return (
    <>
      <Head>
        <title>Next themes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-[#121212] grid place-items-center h-screen">
        <h2 className="text-2xl ">Welcome to Next themes </h2>{" "}
        <Link href="/blogs" className="border-2 border-white">
          {" "}
          Blogs
        </Link>
        <p>current theme is : {theme}</p>
        {currentTheme === "dark" ? (
          <button onClick={() => setTheme("light")}>
            <Image src="/sun.svg" alt="sun" width="150" height="100" />
          </button>
        ) : (
          <button onClick={() => setTheme("dark")}>
            <Image src="/moon.svg" alt="sun" width="150" height="100" />
          </button>
        )}
        <Image src={src} alt="sun" width="150" height="100" />
        <select value={theme} onChange={(e) => setTheme(e.target.value)}>
          <option value="system">System</option>
          <option value="dark">Dark</option>
          <option value="light">Light</option>
        </select>
      </main>
    </>
  );
}
